name = "nanocat-site"
compatibility_date = "2025-06-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "nanocat-db"
database_id = "62dadc12-7632-4e81-b4a1-825992cbea9d"
